"""empty message

Revision ID: 7d274ceeeeb8
Revises: fd6c56a2675a
Create Date: 2025-04-18 17:05:47.567263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d274ceeeeb8'
down_revision = 'fd6c56a2675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('second_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('second_answer', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
