"""empty message

Revision ID: d12a77356c9c
Revises: 7d274ceeeeb8
Create Date: 2025-04-21 16:53:18.230458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12a77356c9c'
down_revision = '7d274ceeeeb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('second_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('second_answer', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
