"""empty message

Revision ID: fd6c56a2675a
Revises: c30aae2aa483
Create Date: 2025-04-17 17:15:51.543741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6c56a2675a'
down_revision = 'c30aae2aa483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
